name: Get HACS
version: "1.3.1"
slug: get
image: "ghcr.io/anhttjavis/{arch}-addon-get"
description: The easiest way to get HACS for Home Assistant
startup: once
boot: manual
url: "https://github.com/anhttjavis/get_hacs/tree/main/get"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
schema:
  channel: list(current|development)?
map:
  - homeassistant_config:rw
